[build]
main = "cmd/server/server/main.go"
cmd = "go build -o bin/api.exe cmd/server/server/main.go"
bin = "bin/api.exe"
poll = true  # Enable polling

[watch]
dirs = ["cmd", "internal", "docs"]  # Directories to watch